services:
  cognitex-landing:
    build: ./cognitex-landing
    ports:
      - "5173:80"
    restart: always

  industry-sentinel:
    build: ./industry-sentinel
    ports:
      - "5175:80"
    restart: always

  personal-sentinel:
    build: ./personal-sentinel
    ports:
      - "5176:80"
    restart: always

  agro-sentinel-web:
    build: ./agro-sentinel/web
    ports:
      - "5174:80"
    restart: always
